#
# Include this file in your .gitlab-ci.yml file to automate & integrate Checkmarx security scans.
#
# These variables can be overridden in your .gitlab-ci.yml file or as envionrment variables.
#

variables:
    BRANCH_NAME: "${CI_COMMIT_REF_NAME}"
    PROJECT_NAME: "$CI_PROJECT_NAME"
    CX_BASE_URI: ${CX_BASE_URI}
    CX_TENANT: ${CX_TENANT}
    CX_CLIENT_ID: ${CX_CLIENT_ID}
    CX_CLIENT_SECRET: ${CX_CLIENT_SECRET}
    ADDITIONAL_PARAMS: ""
    FILE_FILTERS: ""
    CHECKMARX_DOCKER_IMAGE: "ast-cli"

checkmarx-scan:
  stage: test
  image:
    name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
    entrypoint: ['']
  script:
    - echo "${ADDITIONAL_PARAMS}"
    - echo "test"
    - >-
      /app/bin/cx
      scan create
      --project-name ${PROJECT_NAME}
      --file-source '.'
      --branch ${BRANCH_NAME}
      --agent 'Gitlab' 
      ${ADDITIONAL_PARAMS}
